#+Title: Stack-Mode for Emacs
#+Author: Sean Allred
#+Date: [2013-02-28 Thu]

=stack-mode= hopes to be a fully-featured Stack Exchange mode for
Emacs 24+ using version 2.1 (and subsequent versions as available) of
the Stack Exchange API.

For a full list of planned features and explanations of the
implementation (literate programming) thus far, see [[file:stack-mode.org][stack-mode.org]] (if
you're browsing this file via =org-mode=) or [[https://github.com/vermiculus/stack-mode/blob/master/stack-mode.org][the appropriate file
above]] if you're browsing on Github.

Please note that Github does not currently ([2013-02-28 Thu 14:35])
support all embedded source blocks in your web-browser.  I am looking
for a way around this (HTML export comes to mind), but your best
experience with the code-base will come from simply opening the file
in =org-mode=.  Babel (included within distributed copies of
=org-mode= since Emacs 24) is required for extracting the source code
from =stack-mode.org=, so make sure =org-version= is /at least 7.0/
(the current version at time of writing is 7.9.3f).

This README will eventually hold a high-level feature list and details
on installation and configuration.
* Installing
:PROPERTIES:
:ID: D365DE92-82B6-4754-98EA-26E28F1D8916
:END:
- Note taken on [2013-03-01 Fri 01:04] \\
  More work to be done here.  Figure out exactly what needs to be done
  and update the high-level to do it.
Installation is automatic if done through a package manager such as
MELPA; in this case, it is unbefitting to require extra user
involvement.  But, since this is a /literate programming document/,
I'd like to explain how the process could be done manually.

If you are viewing this lovely file in Emacs but are still similarly
'eager' about using =stack-mode=, go ahead and =C-c C-c= [fn::which,
on a default installation, runs =org-babel-execute-src-block=] the
following line.  It will take care of installation for you.  You will
need to confirm execution twice if you have not configured
=org-babel-confirm-evaluate= to allow execuation of Emacs Lisp
snippets without confirmation.

#+call: $install()

(This document does not yet add the necessary files to the
=load-path=.  Please do so manually.)

What we're basically going to do is this:
#+name: $install
#+begin_src emacs-lisp
  (defun $d (m) (message (princ m)) (terpri))
  <<relativize-tangle-references>>
  <<install-tangle-buffer>>
  <<install-move-to-load-path>>
  ;(require 'stack-mode)
#+end_src

oh shit

#+name: relativize-tangle-references
#+begin_src emacs-lisp
  (let ((curdir (replace-regexp-in-string
                 (expand-file-name "~/") "~/"
                 (file-name-directory
                  (or load-file-name buffer-file-name)))))
    (replace-regexp (concat ":tangle \"" curdir "\([A-z-+/.]+\)" "\"") "\1")
    (message curdir))
#+end_src

yeah shit

#+name: install-tangle-buffer
#+begin_src emacs-lisp
  ($d "Tangling stack-mode files...")
  (org-babel-tangle-file "stack-mode.org")
  ($d "Tangling stack-mode files...done")
#+end_src

i'm dumb

#+name: install-move-to-load-path
#+begin_src emacs-lisp
  (message "Moving source files to load-path...")
#+end_src

really dumb

#+name: install-move-to-load-path
#+begin_src emacs-lisp
  (message "More moving...")
#+end_src

* Resources
- [[https://api.stackexchange.com/docs][SX.API v2.1]]
- [[http://stackapps.com/apps/oauth/register][StackApps Registration Page]]
- [[http://www.emacswiki.org/emacs/ModeTutorial][Creating Major Modes for Emacs]]
* Icon
Stack Exchange Mode for Emacs has no explicit use for an icon,
although standard SVG files have been gathered in =resources/= if
anyone would fancy a crack at it.

- [[file:resources/emacs.svg][Emacs icon]]
- [[file:resources/stackexchange.svg][Stack Exchange icon]]

* Credits
Special thanks to
- [[http://stackoverflow.com/users/727827][@tkf]] on StackOverflow
