#+Title: Stack-Mode for Emacs
#+Author: Sean Allred
#+Date: [2013-02-28 Thu]

=stack-mode= hopes to be a fully-featured Stack Exchange mode for
Emacs 24+ using version 2.1 (and subsequent versions as available) of
the Stack Exchange API.

For a full list of planned features and explanations of the
implementation (literate programming) thus far, see [[file:stack-mode.org][stack-mode.org]] (if
you're browsing this file via =org-mode=) or [[https://github.com/vermiculus/stack-mode/blob/master/stack-mode.org][the appropriate file
above]] if you're browsing on Github.

Please note that Github does not currently ([2013-02-28 Thu 14:35])
support all embedded source blocks in your web-browser.  I am looking
for a way around this (HTML export comes to mind), but your best
experience with the code-base will come from simply opening the file
in =org-mode=.  Babel (included within distributed copies of
=org-mode= since Emacs 24) is required for extracting the source code
from =stack-mode.org=, so make sure =org-version= is /at least 7.0/
(the current version at time of writing is 7.9.3f).

This README will eventually hold a high-level feature list and details
on installation and configuration.
